#!/bin/bash

API_KEY="dfe420ea7207942af890db1b61c6c0f5"

CITY_ID="598316"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY="sunny,"
ICON_CLOUDY="cloudy,"
ICON_RAINY="rainy,"
ICON_STORM="stormy,"
ICON_SNOW="snowy,"
ICON_FOG="foggy"

SYMBOL_CELSIUS=" celsius"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_SNOW}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_RAINY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_CLOUDY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_SUNNY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${ICON_FOG}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_FOG}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
else
  echo "${WEATHER_MAIN}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${WEATHER_MAIN}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi#!/bin/bash

kw="windchill_c"
feelslike="$(sed -r "s/.*<$kw>(.*?)<\/$kw>.*/\1/g" <<< $weather)"

if grep -qi 'rain' <<< $condition; then
    icon="⛆"
elif grep -qi 'storm' <<< $condition; then
    icon="⛈"
elif grep -qi 'cloud' <<< $condition; then
    icon="⛅"
elif grep -qi 'clear' <<< $condition; then
    icon="☼"
elif grep -qi 'snow' <<< $condition; then
    icon="⛄"
else
    icon=$condition
fi

firstline="${icon}  ${temperature}°C (${feelslike}°C) "
secondline="${wind:-0}km/h ${humidity}"

echo "${firstline:0:12}"
echo "${secondline:0:12}"